[project]
name = "synthetic-ercot"
version = "0.1.0"
description = "Synthetic ERCOT power grid simulation project"
requires-python = ">=3.11"
dependencies = [
    "gurobipy>=13.0.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pyomo>=6.9.5",
    "pypower>=5.1.19",
    "scipy>=1.17.0",
]
